name: "Test"
on:
  push:
    branches:
      - "master"
jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Initialise Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- --profile minimal --default-toolchain stable -c clippy -y
      - run: |
          cargo clippy -- -D warnings